### ISSUE TITLE
[QUESTION] Jak podejść do CompoundGate

### ISSUE THREAD

**Issue by xederro** [cholewakrzysztof/lab-project#31]
Po tym jak zapis z i do pliku będzie załatwiony, jak podejść do CompoundGate?

- Nowe okienko, tworzymy nasz CompoundGate
- Zapisujemy do konkretnej lokacji na dysku

Po czym otwierając nowy projekt:
- odczytuje dane z tego folderu i na ich podstawie tworzy nowe CompoundGate
- CompoundGate są dostępne w Canvie
- rysujemy używając jakiegoś algorytmu

Po czym odróżniamy czy VirtualIO jest wejsciem czy wyjściem? Poprostu sprawdzać czy ma wyjścia/wejścia?

Tworze Branch by nad tym pracować i proszę go uzywać, zostanie on zaktualizowany odrazu po zamknięciu #29 i #13 oraz po marge [FileManagement](https://github.com/cholewakrzysztof/lab-project/tree/FileManagement) do maina przez @cholewakrzysztof

**Comment by cholewakrzysztof** [comment]
Done zamykam
