### ISSUE TITLE
[BUG] Błąd podczas wczytywania *CompooundGate*, kiedy *message* zawiera spację

### ISSUE THREAD

**Issue by RafalUlikowski** [cholewakrzysztof/lab-project#40]
Otwarcie programu wyrzuca błąd powodowany wczytywaniem *CompoundGate* ze spacja w *message*.

Nie wiem czy to zamierzone, ale zapisywanie takiej bramki także zawiesza program.

**Comment by xederro** [comment]
f6da7ea25ff8433b350280ca77be678a79fb2e0c
