### ISSUE TITLE
[REQUEST] Znaleść funkcje trygonometryczne odpowiadające za ruch

### ISSUE THREAD

**Issue by xederro** [cholewakrzysztof/lab-project#43]
Tak ma wyglądać w założeniu:
dla funkcji 
x(a)=(cos(a)+1)/2
y(a)=(sin(a)+1)/2
<img width="232" alt="image" src="https://github.com/cholewakrzysztof/lab-project/assets/50398562/8281610f-e951-4c98-b644-344ff4591898">

Problemem nie jest łączenie się w jednym miejscu, lecz to że bramka ma kilka wejść które przesuwają to koło w odpowiedni sposób
Funkcje które zwijają do 1 wejścia (nienajlepsze)
x(a)=-(cos(a)+1)/2
y(a)=-(sin(a)+1)/2
Chcemy znaleść funkcję zależną od kąta a, pozycji bramki b, oraz ilości wszystkich bramek n (w programie używane chwilowo n+1)

**Comment by RafalUlikowski** [comment]
![image](https://github.com/cholewakrzysztof/lab-project/assets/29515946/d5e973fd-4202-40df-b5e2-c05fc629b50c)
nie wiem na ile to pomoże, ale jak przemnożysz macierz [x, y] * [ta co wysłałem], to dostaniesz macierz, która będzie miała x i y po obrocie o kąt θ

**Comment by xederro** [comment]
Faktycznie sprawdzę czy wyjdzie to z macierzy obrotu. W sumie nie pomyślałem

**Comment by xederro** [comment]
Niestety. Linie zostają w stałej odległości od siebie, więc cały czas próbują się połączyć tak = co tylko w 2 przypadkach jest akceptowalne

**Comment by xederro** [comment]
https://www.desmos.com/calculator/k5xc5wcrvq
jakby ktoś chciał by się pobawić, dla 2,3,4 działa dla 5 się wywala, myślałem że już to mam ://

**Comment by xederro** [comment]
https://www.desmos.com/calculator/pneutg3rgl to przedstawia koło w zależności od pozycji a oraz ilości wszystkich b, jeżeli wyprowadzimy wzory na sin i cos dla x i y to powinniśmy otrzymać interesujący nas wzór

**Comment by xederro** [comment]
<img width="385" alt="image" src="https://github.com/cholewakrzysztof/lab-project/assets/50398562/21571de6-be79-415e-96bd-3d26b7af2fa6">
